import { Metadata } from 'next';
import  Signin  from '@/components/ui/Signin';



export const metadata: Metadata = {
  title: 'Pro-cleaner-login',
  description: 'Generated by create next app',
};

const SigninPage = () => {
  return <Signin />;
};

export default SigninPage;
