import { Metadata } from 'next';

import Login from '@/components/ui/Login';

export const metadata: Metadata = {
  title: 'Pro-cleaner-login',
  description: 'Generated by create next app',
};

const LoginPage = () => {
  return <Login />;
};

export default LoginPage;
