import Signup from '@/components/ui/Signup';
import { Metadata } from 'next';



export const metadata: Metadata = {
  title: 'Pro-cleaner||Signup',
  description: 'Generated by create next app',
};

const SignupPage = () => {
  return <Signup />;
};

export default SignupPage;
